### ISSUE TITLE
Implement design for 'Last orders' section on profile page

### ISSUE THREAD

**Issue by artursmet** [artursmet/saleor#11]
Design:

![image](https://cloud.githubusercontent.com/assets/1754812/21011073/ccf6b064-bd4f-11e6-8044-c0bc293fef51.png)

**Comment by weronka** [comment]
Page with orders details for unregistered buyers:

![order-details](https://cloud.githubusercontent.com/assets/9913546/21100605/4da537da-c075-11e6-9280-ff57b91e24fa.png)

**Comment by artursmet** [comment]
Implemented as part of userprofile page.
